import urls
import data_handler
from data_handler import Pair
from ontology_handler import update_ontology_graph


def main():
    cf = {'Бамбл санрайз': [Pair(name='Сироп Pinch&Drop «Гренадин»', count='10 мл'),
                            Pair(name='Сок апельсина (фреш)', count='150 мл'),
                            Pair(name='Сироп Pinch&Drop «Кокос»', count='10 мл'),
                            Pair(name='Сироп Pinch&Drop «Маракуйя»', count='20 мл'),
                            Pair(name='Эспрессо', count='60 мл'), Pair(name='Лед', count='150 г')],
          'Фисташковый холодный раф': [Pair(name='Раф Essence «Молочный шоколад с фисташкой»', count='20 г'),
                                       Pair(name='Топпинг Pinch&Drop «Соленая карамель»', count='20 мл'),
                                       Pair(name='Молоко', count='150 мл'),
                                       Pair(name='Эспрессо', count='1 порция (30 мл)')],
          'Фраппучино «\u200eКопченный банан»\u200e': [Pair(name='сухая смесь для фраппе ОДК «Мокко»', count='30 г'),
                                                       Pair(name='молоко', count='100 мл'),
                                                       Pair(name='пюре ОДК «Банан»', count='5 мл'),
                                                       Pair(name='сироп ОДК «Попкорн»', count='5 мл'),
                                                       Pair(name='эспрессо', count='30 мл'),
                                                       Pair(name='лед', count='фраппе (на глаз)')],
          'Раф «Малина-Кокос»': [Pair(name='Основа Raf Cream «Малина-кокос»', count='20 г'),
                                 Pair(name='Молоко', count='200 мл'), Pair(name='Эспрессо', count='30 мл'),
                                 Pair(name='Garnish Cream «Дикая малина»', count='0,5 г')],
          'Tarragon espresso tonic': [Pair(name='Тоник', count='60 мл'), Pair(name='Drinksome Amaro', count='40 мл'),
                                      Pair(name='Сироп «Тархун» Pinch&Drop', count='60 мл'),
                                      Pair(name='Кислая основа «Лайм» Pinch&Drop', count='60 мл'),
                                      Pair(name='Эспрессо', count='15 мл')],
          'Rum tiramisu': [Pair(name='Эспрессо', count='60 мл'),
                           Pair(name='Шоколадный топпинг Pinch&Drop', count='15 мл'),
                           Pair(name='Сироп «Тирамису» Pinch&Drop', count='15 мл'),
                           Pair(name='Печенье Савоярди', count='2 шт'),
                           Pair(name='Drinksome Pirate Dark Rum', count='10 мл'),
                           Pair(name='Взбитые сливки', count='30 г')],
          'Berry whiskey a la affogato': [Pair(name='Эспрессо', count='60 мл'),
                                          Pair(name='Drinksome Highland Scotch Whiskey', count='25 мл'),
                                          Pair(name='Пюре «Клубника» Pinch&Drop', count='30 мл'),
                                          Pair(name='Ванильное мороженое', count='50 г'),
                                          Pair(name='Взбитые сливки', count='30 г')],
          'Amaro banana tini': [Pair(name='Drinksome Amaro', count='20 мл'),
                                Pair(name='Концентрат «Банан» фруктовый ODK', count='20 мл'),
                                Pair(name='Сироп «Шоколадное Печенье» ODK', count='10 мл'),
                                Pair(name='Эспрессо', count='20 мл'),
                                Pair(name='Drinksome Orange Angobitter', count='15 мл'),
                                Pair(name='Drinksome Aromatic Angobitter', count='5 капель')],
          'Coffee mulled wine': [Pair(name='Колд-брю Руанда Doppio', count='220 мл'),
                                 Pair(name='Drinksome Siberian Aperitif', count='30 мл'),
                                 Pair(name='Сироп «Зеленое яболоко» Pinch&Drop', count='10 мл'),
                                 Pair(name='Кислая основа «Лайм» Pinch&Drop', count='5 мл')],
          'Pirate Ice latte': [Pair(name='Эспрессо', count='60 мл'),
                               Pair(name='Drinksome Pirate Dark Rum', count='40 мл'),
                               Pair(name='Молоко 2,5 %', count='60 мл'), Pair(name='Сливки 10 %', count='60 мл'),
                               Pair(name='Сироп «Ваниль» Pinch&Drop', count='15 мл')],
          'Floral espresso-tonic': [Pair(name='Розовый тоник', count='60 мл'),
                                    Pair(name='Drinksome Red Vermouth', count='40 мл'),
                                    Pair(name='Сироп «Дамасская роза» Pinch&Drop', count='60 мл'),
                                    Pair(name='Кислая основа «Лайм» Pinch&Drop', count='60 мл'),
                                    Pair(name='Эспрессо', count='15 мл')],
          'Espresso Cherry Tonic': [Pair(name='Сироп Pinch&Drop «Македонская вишня»', count='15 мл'),
                                    Pair(name='Сироп Pinch&Drop «Шоколад»', count='5 мл'),
                                    Pair(name='Эспрессо', count='30 мл'), Pair(name='Тоник', count='100 мл')],
          'Bananza': [Pair(name='Пюре Pinch&Drop «Банан»', count='15 мл'),
                      Pair(name='Сироп Pinch&Drop «Макадамия»', count='5 мл'),
                      Pair(name='Миндальное молоко', count='30 мл'), Pair(name='Эспрессо', count='100 мл'),
                      Pair(name='Арахисовая паста', count='1 чайная ложка')],
          'Tutti Tamma': [Pair(name='Сироп Pinch&Drop «Баббл Гам»', count='15 мл'),
                          Pair(name='Сироп Pinch&Drop «Земляника»', count='10 мл'), Pair(name='Молоко', count='180 мл'),
                          Pair(name='Эспрессо', count='50 мл')],
          'Sunrise': [Pair(name='Сироп ОDК «Шоколадное печенье»', count='10 мл'),
                      Pair(name='Пюре ОDК «Вишня»', count='20 мл'), Pair(name='Нитро кофе', count='120 мл'),
                      Pair(name='Сливки взбитые', count='на глаз'), Pair(name='Лед', count='5-7 шт')],
          'Нитро Ананас': [Pair(name='Сироп ОDК «Ананас»', count='15 мл'),
                           Pair(name='Сироп ОDК «Бузина»', count='10 мл'), Pair(name='Кофе', count='60 мл'),
                           Pair(name='Лед', count='1 шарик')],
          'Герой': [Pair(name='Пюре ODK «Красный Апельсин»', count='20 мл'),
                    Pair(name='Сироп ODK «Соленая Карамель»', count='10 мл'),
                    Pair(name='Концентрат ODK «Лимон»', count='20 мл'), Pair(name='Эспрессо', count='30 мл'),
                    Pair(name='Тоник', count='100 мл'), Pair(name='Лед', count='5-7 шт')],
          'Hot banana cookies': [Pair(name='пюре ODK «Кокос»', count='10 мл'),
                                 Pair(name='сиропа ODK «Спекулос печенье»', count='10 мл'),
                                 Pair(name='двойного эспрессо', count='60 мл'),
                                 Pair(name='бананового молока', count='150 мл')],
          'Смородиновый бархат': [Pair(name='сиропа ODK «Черная смородина»', count='10 мл'),
                                  Pair(name='сиропа ODK «Бобы Тонка»', count='20 мл'),
                                  Pair(name='нитро-кофе', count='70 мл'), Pair(name='концентрата лимона', count='5 мл'),
                                  Pair(name='5-7 кубиков льда', count='0')],
          'Флэт уайт с мятным брауни': [Pair(name='молока', count='150 мл'),
                                        Pair(name='двойного эспрессо', count='60 мл'),
                                        Pair(name='сиропа P&D «Брауни»', count='10 мл'),
                                        Pair(name='сиропа P&D «Мятная конфета»', count='5 мл')],
          'Раф-кофе Персиковый пирог': [Pair(name='молока', count='70 мл'), Pair(name='сливок 11%', count='70 мл'),
                                        Pair(name='двойного эспрессо', count='60 мл'),
                                        Pair(name='сиропа P&D «Персиковый пирог»', count='15 мл')],
          'Холодный кофе Нитро-орешек': [Pair(name='сиропа ODK «Кардамон»', count='10 мл'),
                                         Pair(name='сиропа ODK «Лесной Орех»', count='20 мл'),
                                         Pair(name='нитро-кофе', count='150 мл')],
          'Освежающий кофе-тоник с малиной': [Pair(name='сиропа ODK «Малина»', count='15 мл'),
                                              Pair(name='сиропа ODK «Перечная Мята»', count='10 мл'),
                                              Pair(name='эспрессо', count='1 шот'),
                                              Pair(name='индиан тоника', count='100 мл')],
          'Холодный кофе Черная смородина-трипл сек': [
              Pair(name='сиропа Pinch&Drop «Чёрная смородина»', count='10 мл'),
              Pair(name='сиропа Pinch&Drop «Трипл-сек»', count='10 мл'), Pair(name='молока', count='150 мл'),
              Pair(name='колд-брю', count='30 мл')],
          'Холодный кофе Персик-банан': [Pair(name='сиропа Pinch&Drop «Персик»', count='15 мл'),
                                         Pair(name='сиропа Pinch&Drop «Желтый банан»', count='10 мл'),
                                         Pair(name='молока', count='150 мл'), Pair(name='колд-брю', count='30 мл'),
                                         Pair(name='бананового нектара', count='40 мл')], 'Подсоленный кофе-тоник': [
            Pair(name='кордиала C.O.D.E «Апельсин Фукумото / Французская Ваниль / Соль»', count='30 мл'),
            Pair(name='сиропа ODK «Соленая карамель»', count='20 мл'), Pair(name='лаймового сока', count='20 мл'),
            Pair(name='индиан тоника', count='100 мл'), Pair(name='эспрессо', count='1 шот')],
          'Романтичное утро': [Pair(name='Cироп ODK «Амаретто»', count='15 мл'),
                               Pair(name='Cироп ODK «Фалернум»', count='10 мл'), Pair(name='Эспрессо', count='2 шт'),
                               Pair(name='Сливки 10%', count='70 мл'), Pair(name='Молоко', count='70 мл')],
          'Цветочный раф с черной смородиной': [
              Pair(name='сироп P&D «Прованская Лаванда» сироп P&D «Чёрная смородина» 10 мл', count='10 мл'),
              Pair(name='эспрессо порция', count='0'), Pair(name='молоко сливки 10% 75 мл', count='75 мл')],
          'Кофейный напиток с бананом и баббл гамом': [Pair(name='сироп P&D «Жёлтый банан»', count='15 мл'),
                                                       Pair(name='америка но (на двойном эспрессо порция', count='0'),
                                                       Pair(name='пена со вкусом «Баббл Гам»', count='50 мл')],
          'Раф тыквенно-карамельный': [Pair(name='Сироп «Пряная тыква»', count='10 мл'),
                                       Pair(name='Сироп «Ореховая карамель»', count='10 мл'),
                                       Pair(name='Эспрессо', count='30 мл'), Pair(name='Молоко', count='75 мл'),
                                       Pair(name='Сливки 75 мл', count='11 %')],
          'Раф с имбирным пряником': [Pair(name='сиропа «Имбирный пряник»', count='30 мл'),
                                      Pair(name='эспрессо (30 мл)', count='1 порция'),
                                      Pair(name='сливок 10%', count='75 мл'), Pair(name='молока', count='75 мл')],
          'Айс-латте с имбирным пряником': [Pair(name='сиропа «Имбирный пряник»', count='20 мл'),
                                            Pair(name='кусковой лёд', count='0'),
                                            Pair(name='эспрессо (30 мл)', count='1 порция'),
                                            Pair(name='молока', count='100 мл')],
          'Сливочный латте с мятой': [Pair(name='сиропа Pinch&Drop «Зелёная мята»', count='10 мл'),
                                      Pair(name='топпинга Pinch&Drop «Белый шоколад»', count='20 мл'),
                                      Pair(name='молотой корицы', count='1 щепотка'),
                                      Pair(name='эспрессо (60 мл)', count='2 порции'),
                                      Pair(name='кокосового молока', count='250 мл')],
          'Грушевый раф с масалой': [Pair(name='топпинга Pinch&Drop «Кленовый сироп»', count='10 мл'),
                                     Pair(name='сиропа Pinch&Drop «Груша»', count='20 мл'),
                                     Pair(name='смеси масала', count='1 щепотка'),
                                     Pair(name='эспрессо (60 мл)', count='2 порции'),
                                     Pair(name='молока', count='50 мл'), Pair(name='сливок 11%', count='70 мл')],
          'Безалкогольный пунш с кофе': [Pair(name='сиропа Pinch&Drop «Кокос»', count='10 мл'),
                                         Pair(name='сиропа Pinch&Drop «Гренадин»', count='20 мл'),
                                         Pair(name='корицы', count='1 палочка'),
                                         Pair(name='бадьяна', count='2 звёздочки'),
                                         Pair(name='черного перца', count='3 горошины'),
                                         Pair(name='гвоздики', count='4 бутона'), Pair(name='грейпфрута', count='30 г'),
                                         Pair(name='апельсинового сока', count='30 мл'),
                                         Pair(name='яблочного сока', count='30 мл'),
                                         Pair(name='кофе, заваренного альтернативным методом', count='170 мл')],
          'Коктейль Пряная сливочная тыква': [Pair(name='сиропа Pinch&Drop «Лесной орех»', count='10 мл'),
                                              Pair(name='сиропа Pinch&Drop «Солёная карамель»', count='10 мл'),
                                              Pair(name='молотой куркумы', count='1 щепотка'),
                                              Pair(name='молотой корицы', count='1 щепотка'),
                                              Pair(name='эспрессо (30 мл)', count='1 порция'),
                                              Pair(name='сока манго', count='30 мл'),
                                              Pair(name='молока', count='50 мл'),
                                              Pair(name='пюре из запечённой тыквы', count='50 мл')],
          'Baby-раф с ореховый крем-брюле': [Pair(name='топпинга «Шоколадно-ореховый»', count='15 мл'),
                                             Pair(name='сиропа «Крем брюле»', count='20 мл'),
                                             Pair(name='эспрессо (30 мл)', count='1 порция'),
                                             Pair(name='сливок 11%', count='75 мл'),
                                             Pair(name='молока', count='75 мл')],
          'Грушевый крем-латте': [Pair(name='сиропа\xa0«Нуга»', count='10 мл'),
                                  Pair(name='пюре\xa0«Груша Вильямс»', count='15 мл'),
                                  Pair(name='кускового льда', count='1 бокал'),
                                  Pair(name='эспрессо (30 мл)', count='1 порция'),
                                  Pair(name='соевого молока', count='120 мл')],
          'Айс-кофе Нуга в шоколаде': [Pair(name='сиропа «Нуга»', count='10 мл'),
                                       Pair(name='сухой смеси «Шоколад»', count='15 г'),
                                       Pair(name='эспрессо (30 мл)', count='1 порция'),
                                       Pair(name='льда', count='5 кубиков'),
                                       Pair(name='мягкого мороженого', count='40 г'),
                                       Pair(name='молока', count='120 мл')],
          'Холодный флэт с солёной карамелью': [Pair(name='сиропа «Нуга»', count='10 мл'),
                                                Pair(name='сиропа «Солёная Карамель»', count='15 мл'),
                                                Pair(name='сухой смеси «Кофе»', count='15 г'),
                                                Pair(name='кускового льда', count='1 бокал'),
                                                Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                Pair(name='мягкого мороженого', count='40 г'),
                                                Pair(name='молока', count='120 мл')],
          'Свекольный айс-латте': [Pair(name='сиропа\xa0«Малина»', count='10 мл'),
                                   Pair(name='пюре\xa0«Свёкла»', count='30 мл'),
                                   Pair(name='кускового льда', count='1 бокал'), Pair(name='паприки', count='1 г'),
                                   Pair(name='эспрессо (30 мл)', count='1 порция'),
                                   Pair(name='молока', count='120 мл')],
          'Раф с арахисовым печеньем и зимними специями': [Pair(name='сиропа «Арахисовое печенье»', count='20 мл'),
                                                           Pair(name='сиропа «Зимние специи»', count='20 мл'),
                                                           Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                           Pair(name='сливок 11%', count='100 мл'),
                                                           Pair(name='молока', count='100 мл')],
          'Капучино XXL со вкусом медовика и бобов тонка': [Pair(name='сиропа «Медовик»', count='20 мл'),
                                                            Pair(name='сиропа «Бобы тонка»', count='20 мл'),
                                                            Pair(name='эспрессо (60 мл)', count='2 порции'),
                                                            Pair(name='молока', count='250 мл')],
          'Латте с имбирным пряником и пралине': [Pair(name='сиропа «Имбирный пряник»', count='10 мл'),
                                                  Pair(name='сиропа «Пралине»', count='10 мл'),
                                                  Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                  Pair(name='молока', count='150 мл')],
          'Эспрессо с барбадосской вишней и розовым перцем': [Pair(name='сиропа «Розовый перец»', count='5 мл'),
                                                              Pair(name='сиропа «Барбадосская вишня»', count='10 мл'),
                                                              Pair(name='эспрессо (30 мг)', count='1 порция')],
          'Ведьминский раф': [Pair(name='сиропа «Пряная тыква»', count='20 мл'),
                              Pair(name='сиропа «Мёд»', count='20 мл'), Pair(name='эспрессо (30 мл)', count='1 порция'),
                              Pair(name='молока', count='70 мл'), Pair(name='сливок 10%', count='70 мл')],
          'Раф с миндалём и кунжутом': [Pair(name='сиропа «Медовик»', count='20 мл'),
                                        Pair(name='сиропа «Миндаль»', count='20 мл'),
                                        Pair(name='взбитые сливки (украшение)', count='0'),
                                        Pair(name='кондитерская посыпка (украшение)', count='0'),
                                        Pair(name='Маршмеллоу (украшение)', count='0'),
                                        Pair(name='эспрессо (30 мл)', count='1 порция'),
                                        Pair(name='л. кунжута (2,7 г)', count='1 ч.'),
                                        Pair(name='кунжутного масла', count='5 мл'), Pair(name='сливок', count='50 мл'),
                                        Pair(name='миндального молока', count='200 мл')],
          'Фраппучино (Frappuccino)': [Pair(name='соуса для десерта «Фраппе Ваниль»', count='30 мл'),
                                       Pair(name='1,5 г маркера для латте-арта «Шоколад» (украшение)', count='0'),
                                       Pair(name='взбитые сливки (украшение)', count='0'),
                                       Pair(name='эспрессо (60 мл)', count='2 порции'),
                                       Pair(name='молока', count='60 мл')],
          'Нитро-латте с арахисовым печеньем': [Pair(name='сиропа «Арахисовое печенье»', count='100 мл'),
                                                Pair(name='молока', count='150 мл'),
                                                Pair(name='сливок', count='150 мл'),
                                                Pair(name='кофе колд-брю', count='600 мл')],
          'Айс-латте с мармеладом': [Pair(name='сиропа «Бабл гам»', count='20 мл'),
                                     Pair(name='взбитые сливки (украшение)', count='0'),
                                     Pair(name='лёд кусковой и фраппе', count='0'),
                                     Pair(name='мармелад (украшение)', count='0'),
                                     Pair(name='эспрессо (30 мл)', count='1 порция'),
                                     Pair(name='крепко заваренного чая анчан', count='10 мл'),
                                     Pair(name='молока', count='170 мл')],
          'Коктейль Айсберг с голубым чаем матча': [Pair(name='сиропа\xa0«Личи»', count='10 мл'),
                                                    Pair(name='сиропа\xa0«Пралине»', count='20 мл'),
                                                    Pair(name='лёд (кусковой и фраппе)', count='0'),
                                                    Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                    Pair(name='голубого чая матча', count='5 г'),
                                                    Pair(name='молока', count='170 мл')],
          'Нитро-кофе бамбл': [Pair(name='сиропа «Апельсиновый сприц»', count='30 мл'),
                               Pair(name='сиропа «Розовый перец»', count='50 мл'),
                               Pair(name='цедра апельсина', count='0'), Pair(name='розовый перец горошком', count='0'),
                               Pair(name='апельсинового фреша', count='300 мл'),
                               Pair(name='кофе колд-брю', count='600 мл')],
          'Цитрусовый нитро-кофе': [Pair(name='сиропа «Мохито»', count='30 мл'),
                                    Pair(name='сиропа «Бергамот»', count='60 мл'),
                                    Pair(name='долька бергамота (украшение)', count='0'),
                                    Pair(name='Спрайт или 7 up', count='200 мл'),
                                    Pair(name='кофе колд-брю', count='700 мл')],
          'Веган колд-брю Груша с чаем матча': [Pair(name='сиропа «Зелёный чай матча»', count='10 мл'),
                                                Pair(name='пюре «Груша Вильямс»', count='20 мл'),
                                                Pair(name='лёд кусковой и фраппе', count='0'),
                                                Pair(name='грушевый чипс (украшение)', count='0'),
                                                Pair(name='чай матча', count='0'),
                                                Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                Pair(name='соевого молока', count='80 мл')],
          'Латте с Фалернумом и печеньем Спекулос': [Pair(name='сиропа\xa0«Фалернум»', count='10 мл'),
                                                     Pair(name='сиропа\xa0«Печенье Спекулос»', count='20 мл'),
                                                     Pair(name='1,5 г маркера для латте-арта «Шоколад» (украшение)',
                                                          count='0'), Pair(name='печенье (украшение)', count='1 шт'),
                                                     Pair(name='звездочка аниса (украшение)', count='1 шт'),
                                                     Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                     Pair(name='1,5 г взбитых сливок (украшение)', count='0'),
                                                     Pair(name='молока', count='120 мл')],
          'Раф Груша с розой': [Pair(name='сиропа ODK «Роза»', count='10 мл'),
                                Pair(name='пюре ODK «Груша Вильямс»', count='15 мл'),
                                Pair(name='вафельная роза (украшение)', count='1 шт.'),
                                Pair(name='кондитерский блеск (украшение)', count='1 щепотка'),
                                Pair(name='молотый мускатный орех', count='1 щепотка'),
                                Pair(name='молотая корица', count='1 щепотка'),
                                Pair(name='эспрессо (30 мл)', count='1 порция'),
                                Pair(name='взбитые сливки со вкусом розы (украшение)', count='30 г'),
                                Pair(name='молоко', count='100 мл'), Pair(name='сливки 10%', count='100 мл')],
          'Чёрный капучино Ванильная сладкая вата': [Pair(name='сиропа «Сладкая вата»', count='10 мл'),
                                                     Pair(name='сиропа «Французская ваниль»', count='20 мл'),
                                                     Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                     Pair(name='соли', count='2 г'),
                                                     Pair(name='пищевого угля (порошок)', count='6 г'),
                                                     Pair(name='молока', count='170 мл')],
          'Раф груша со сладкой ватой': [Pair(name='сиропа «Сладкая вата»', count='20 мл'),
                                         Pair(name='пюре «Груша Вильямс»', count='30 мл'),
                                         Pair(name='1,5 г топпинга «Карамель» маркер для латте-арта (украшение)',
                                              count='0'), Pair(name='сладкой ваты (украшение)', count='1 слой'),
                                         Pair(name='молотого мускатного ореха', count='1 щепотка'),
                                         Pair(name='эспрессо (30 мл)', count='1 порция'),
                                         Pair(name='1,5 г взбитых сливок (украшение)', count='0'),
                                         Pair(name='сливок 10%', count='200 мл')],
          'Капучино Амаретто с розовым перцем': [Pair(name='сиропа «Амаретто»', count='10 мл'),
                                                 Pair(name='сиропа «Розовый перец»', count='10 мл'), Pair(
                  name='1,5 топпинга маркер для латте-арта «Шоколад» (украшение)', count='мл'),
                                                 Pair(name='розового перца горошком (украшение)', count='1 г'),
                                                 Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                 Pair(name='соевого молока', count='120 мл')],
          'Кола де моно (Cola de mono) из Чили': [Pair(name='сиропа «Корица»', count='10 мл'),
                                                  Pair(name='сиропа «Французская ваниль»', count='20 мл'),
                                                  Pair(name='кусковой лёд', count='0'),
                                                  Pair(name='мускатного ореха', count='1 щепотка'),
                                                  Pair(name='корицы', count='1 палочка'),
                                                  Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                  Pair(name='гвоздики', count='3 бутона'),
                                                  Pair(name='золотого рома', count='30 мл'),
                                                  Pair(name='молока', count='100 мл')],
          'Кофе Бамбл американо': [Pair(name='сиропа «Мёд»', count='20 мл'),
                                   Pair(name='какао (украшение)', count='1 щепотка'),
                                   Pair(name='1,5 г взбитых сливок (украшение)', count='0'),
                                   Pair(name='апельсиновой цедры (украшение)', count='2 слайса'),
                                   Pair(name='зефира Маршмеллоу (украшение)', count='30 г'),
                                   Pair(name='апельсинового сока', count='50 мл'),
                                   Pair(name='кофе американо', count='180 мл')],
          'Альтернативный кофе Спайси': [Pair(name='сиропа «Острый»', count='20 мл'),
                                         Pair(name='л. арахисовой пасты', count='1 ч.'),
                                         Pair(name='льда', count='1 кубик'),
                                         Pair(name='перца чили (украшение)', count='1 щепотка'),
                                         Pair(name='какао (украшение)', count='1 щепотка'),
                                         Pair(name='', count='1 финик'),
                                         Pair(name='эспрессо (30 мл)', count='1 порция'),
                                         Pair(name='1,5 г взбитых сливок (украшение)', count='0'),
                                         Pair(name='арахиса (украшение)', count='4 ореха'),
                                         Pair(name='зефира Маршмеллоу (украшение)', count='30 г'),
                                         Pair(name='воды', count='120 мл')],
          'Раф Любовь-морковь': [Pair(name='сиропа «Пралине»', count='20 мл'),
                                 Pair(name='пюре «Морковь»', count='30 мл'),
                                 Pair(name='эспрессо (30 мл)', count='1 порция'),
                                 Pair(name='сливок 10%', count='50 мл'), Pair(name='молока', count='70 мл')],
          'Морковный раф': [Pair(name='пюре «Морковь»', count='30 мл'), Pair(name='эспрессо (40 мл)', count='1 порция'),
                            Pair(name='молока', count='50 мл'), Pair(name='сливок 10%', count='70 мл')],
          'Коктейль Кощей бессмертный': [Pair(name='сиропа Pinch&Drop «Амаретто»', count='25 мл'),
                                         Pair(name='лёд фраппе', count='0'),
                                         Pair(name='эспрессо (30 мл)', count='1 порция'),
                                         Pair(name='безалкогольного пива', count='120 мл')],
          'Золотой веганский латте': [Pair(name='сиропа «Французская ваниль»', count='20 мл'),
                                      Pair(name='эспрессо (30 мг)', count='1 порция'),
                                      Pair(name='куркумы', count='2 г'),
                                      Pair(name='овсяного молока (или любого другого вида альтернативного молока)',
                                           count='200 мл')],
          'Айс-раф банановая карамель': [Pair(name='сиропа P&D\xa0«Желтый банан»', count='10 мл'),
                                         Pair(name='сиропа P&D\xa0«Карамель»', count='10 мл'),
                                         Pair(name='кусковой лед', count='0'),
                                         Pair(name='эспрессо (30 мл)', count='1 порция'),
                                         Pair(name='сливок 10%', count='50 мл'), Pair(name='молока', count='150 мл')],
          'Коктейль Лимонный тарт с миндалём': [Pair(name='сиропа Pinch&Drop «Лимонный тарт»', count='20 мл'),
                                                Pair(name='сиропа Pinch&Drop «Миндаль»', count='20 мл'),
                                                Pair(name='кусковой лёд', count='0'),
                                                Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                Pair(name='содовой', count='100 мл'),
                                                Pair(name='молока', count='130 мл')],
          'Коктейль Мятное яблоко': [Pair(name='концентрированного сока лайма Pinch&Drop', count='10 мл'),
                                     Pair(name='сиропа Pinch&Drop «Зелёное яблоко»', count='20 мл'),
                                     Pair(name='сиропа Pinch&Drop «Мятная конфета»', count='20 мл'),
                                     Pair(name='кусковой лёд', count='0'),
                                     Pair(name='кофе колд брю (30 мл)', count='1 порция'),
                                     Pair(name='воды', count='100 мл')],
          'Коктейль В кинотеатр': [Pair(name='сиропа Pinch&Drop «Лесной орех»', count='10 мл'),
                                   Pair(name='сиропа Pinch&Drop «Попкорн»', count='20 мл'),
                                   Pair(name='кусковой лёд', count='0'),
                                   Pair(name='эспрессо (30 мл)', count='1 порция'),
                                   Pair(name='молока', count='130 мл')],
          'Коктейль Мандариновый рай': [Pair(name='сиропа Pinch&Drop «Ваниль»', count='10 мл'),
                                        Pair(name='сиропа Pinch&Drop «Мандарин»', count='20 мл'),
                                        Pair(name='кусковой лёд', count='0'),
                                        Pair(name='эспрессо (30 мл)', count='1 порция'),
                                        Pair(name='тоника', count='100 мл')],
          'Тибетский раф': [Pair(name='сиропа «Ирис»', count='10 мл'),
                            Pair(name='сиропа «Чёрный чай Масала»', count='15 мл'),
                            Pair(name='эспрессо (30 мл)', count='1 порция'),
                            Pair(name='0,5 гр мускатного ореха', count='0'), Pair(name='аниса', count='5 гр'),
                            Pair(name='сливок 10%', count='150 мл')],
          'Ромовый мокко': [Pair(name='сиропа «Мёд»', count='10 мл'), Pair(name='пюре «Черника»', count='15 мл'),
                            Pair(name='базы «Шоколад»', count='15 гр'), Pair(name='эспрессо (30 мл)', count='1 порция'),
                            Pair(name='бренди Арарат Coffee', count='30 мл'), Pair(name='молока', count='150 мл')],
          'Альпийский раф': [Pair(name='сиропа «Белый шоколад»', count='10 мл'),
                             Pair(name='сиропа «Кюрасао Трипл сек»', count='15 мл'),
                             Pair(name='0,3 гр Специи "Апельсиновый перец" Kotanyi (на украшение)', count='0'),
                             Pair(name='0,5 гр Специи "Апельсиновый перец" Kotanyi (в состав рафа)', count='0'),
                             Pair(name='эспрессо (30 мл)', count='1 порция'),
                             Pair(name='чипс "апельсин в шоколаде"', count='10 гр'),
                             Pair(name='сливок 10%', count='150 мл')],
          'Капучино Пряная груша': [Pair(name='сиропа Pinch&Drop «Груша»', count='10 мл'),
                                    Pair(name='сиропа Pinch&Drop «Имбирный пряник»', count='10 мл'),
                                    Pair(name='эспрессо (30 мл)', count='1 порция'),
                                    Pair(name='молока', count='170 мл')],
          'Раф-кофе Солёная карамель': [Pair(name='сиропа Pinch&Drop «Солёная карамель»', count='20 мл'),
                                        Pair(name='эспрессо (60 мл)', count='2 порции'),
                                        Pair(name='11% сливок', count='100 мл'), Pair(name='молока', count='100 мл')],
          'Банановый латте с лимонным тартом': [Pair(name='сиропа Pinch&Drop «Лимонный тарт»', count='10 мл'),
                                                Pair(name='сиропа Pinch&Drop «Желтый банан»', count='10 мл'),
                                                Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                Pair(name='молока', count='200 мл')],
          'Американо со сливками': [Pair(name='сиропа Pinch&Drop «Айриш Крем»', count='10 мл'),
                                    Pair(name='эспрессо (30 мл)', count='1 порция'),
                                    Pair(name='кипятка', count='120 мл')],
          'Холодный миндальный раф с медом': [Pair(name='сиропа\xa0«Миндаль»', count='15 мл'),
                                              Pair(name='сиропа\xa0«Мёд»', count='15 мл'),
                                              Pair(name='кусковой лёд', count='0'),
                                              Pair(name='эспрессо (30 мл)', count='1 порция'),
                                              Pair(name='молока', count='75 мл'),
                                              Pair(name='сливок 10%', count='75 мл')],
          'Нитро-латте Банановый крем-брюле': [Pair(name='сиропа «Крем-брюле»', count='40 мл'),
                                               Pair(name='сиропа «Зелёный банан»', count='60 мл'),
                                               Pair(name='молока', count='150 мл'),
                                               Pair(name='сливок 10%', count='150 мл'),
                                               Pair(name='кофе колд-брю', count='600 мл')],
          'Айс-кофе Черные ягоды в молоке': [Pair(name='сиропа Pinch&Drop «Черная смородина»', count='10 мл'),
                                             Pair(name='сиропа Pinch&Drop «Ежевика»', count='10 мл'),
                                             Pair(name='кусковой лед', count='0'),
                                             Pair(name='эспрессо (30 мл)', count='1 порция'),
                                             Pair(name='молока', count='150 мл')],
          'Айс-кофе Бамблби и фейхоа': [Pair(name='концентрированного сока лимона Pinch&Drop', count='10 мл'),
                                        Pair(name='сиропа Pinch&Drop «Фейхоа»', count='20 мл'),
                                        Pair(name='кусковой лёд', count='0'),
                                        Pair(name='эспрессо (30 мл)', count='1 порция'),
                                        Pair(name='ананасового сока', count='100 мл')],
          'Цитрусовый айс-кофе': [Pair(name='сиропа Pinch&Drop «Мандарин»', count='10 мл'),
                                  Pair(name='сиропа Pinch&Drop «Лимонный тарт»', count='10 мл'),
                                  Pair(name='кусковой лёд', count='0'), Pair(name='эспрессо (30 мл)', count='1 порция'),
                                  Pair(name='тоника', count='100 мл')],
          'Айс-кофе Клубника с мятой': [Pair(name='сиропа Pinch&Drop «Мятная конфета»', count='10 мл'),
                                        Pair(name='сиропа Pinch&Drop «Клубника»', count='20 мл'),
                                        Pair(name='кусковой лёд', count='0'),
                                        Pair(name='эспрессо (30 мл)', count='1 порция'),
                                        Pair(name='молока', count='150 мл')],
          'Айс-раф с бананом и медом': [Pair(name='сиропа P&D\xa0«Желтый банан»', count='15 мл'),
                                        Pair(name='топпига P&D\xa0«Мед»', count='15 мл'),
                                        Pair(name='кусковой лед', count='0'),
                                        Pair(name='эспрессо (30 мл)', count='1 порция'),
                                        Pair(name='молока', count='75 мл'), Pair(name='сливок 10%', count='75 мл')],
          'Айс-латте с бананом и соленой карамелью': [Pair(name='сиропа MONIN «Зелёный банан»', count='20 мл'),
                                                      Pair(name='сиропа MONIN «Солёная карамель»', count='20 мл'),
                                                      Pair(name='кусковой лёд', count='0'),
                                                      Pair(name='эспрессо (30 мл)', count='1 порция'),
                                                      Pair(name='молока', count='150 мл')],
          'Холодный яблочный кофе с орехом': [Pair(name='сиропа Pinch&Drop «Лесной орех»', count='10 мл'),
                                              Pair(name='сиропа Pinch&Drop «Яблочный пирог»', count='20 мл'),
                                              Pair(name='кусковой лёд', count='0'),
                                              Pair(name='эспрессо (30 мл)', count='1 порция'),
                                              Pair(name='молока', count='130 мл')],
          'Каштановый айс-кофе с тоником': [Pair(name='сиропа «Каштан»', count='30 мл'),
                                            Pair(name='кусковой лёд', count='0'),
                                            Pair(name='эспрессо (30 мл)', count='1 порция'),
                                            Pair(name='тоника', count='150 мл')],
          'Кофе По-Гречески': [Pair(name='Кофе молотый Doppio «Дамбри Фолз»', count='7 / 15 г'),
                               Pair(name='Вода', count='70 / 150 мл'), Pair(name='Сахар', count='240 мл')],
          'Кофе Айриш с Макадамией': [Pair(name='Эспрессо Doppio «Бразилия Суль Де Минас»', count='60 мл'),
                                      Pair(name='Горячая вода', count='90 мл'),
                                      Pair(name='Напиток б/а Drinksome «Шотландский виски»', count='30 мл'),
                                      Pair(name='Сироп Pinch&Drop «Макадамия»', count='25 мл'),
                                      Pair(name='Сливки растительные Chantypak', count='25 мл'),
                                      Pair(name='Молоко', count='25 мл')],
          'Латте Крем-Брюле Миндаль': [Pair(name='Молоко Parmalat 3,5%', count='220 мл'),
                                       Pair(name='Сироп Pinch&Drop «Крем Брюле»', count='20 мл'),
                                       Pair(name='Сироп Pinch&Drop «Амаретто»', count='10 мл'),
                                       Pair(name='Эспрессо Doppio «Бленд №3»', count='30 мл'),
                                       Pair(name='Пенка сливочная', count='50 мл')],
          'Латте Груша-Бобы Тонка': [Pair(name='Тапиока карамельная', count='40 г'),
                                     Pair(name='Молоко Parmalat 3,5%', count='270 мл'),
                                     Pair(name='Сироп Pinch&Drop «Груша Конференция»', count='20 мл'),
                                     Pair(name='Сироп Pinch&Drop «Македонская вишня»', count='10 мл'),
                                     Pair(name='Сироп ODK «Бобы Тонка»', count='10 мл'),
                                     Pair(name='Эспрессо Doppio «Бленд №5»', count='30 мл')],
          'Раф Тирамису': [Pair(name='Эспрессо Doppio «Бразилия Суль Де Минас»', count='1 порция'),
                           Pair(name='Молоко', count='75 мл'), Pair(name='Сливки 10%', count='75 мл'),
                           Pair(name='Б/а напиток Drinksome «Темный ром»', count='35 мл'),
                           Pair(name='Сироп Pinch&Drop «Тирамису»', count='15 мл')],
          'Имбирный скотч': [Pair(name='Эспрессо Doppio «Бленд No 5»', count='1 порция'),
                             Pair(name='Молоко', count='160 мл'),
                             Pair(name='Б/а напиток Drinksome «Шотландский виски»', count='30 мл'),
                             Pair(name='Б/а напиток Drinksome «Тигровый биттер»', count='10 мл'),
                             Pair(name='Сироп Pinch&Drop «Имбирный пряник»', count='10 мл')],
          'The Big Lebowski': [Pair(name='Doppio «Бленд No5» для эспрессо', count='50мл'),
                               Pair(name='водка', count='30мл'),
                               Pair(name='сироп ODK «Соленая Карамель»', count='10мл'),
                               Pair(name='ореховая пена на основе сиропа ODK *', count='на глаз'),
                               Pair(name='лед кусковой', count='3-4 шт')],
          'Аэрокано Личи-белый Лотос': [Pair(name='эспрессо', count='60 мл'),
                                        Pair(name='сироп Pinch&Drop «Карамель»', count='20 мл'),
                                        Pair(name='кордиал C.O.D.E «Личи / Белый Лотос / Кардамон»', count='30 мл'),
                                        Pair(name='лед', count='150 г')],
          'Айс-капучино Хмельной Маршмеллоу': [Pair(name='Drinksome «Шотландский виски»', count='30 мл'),
                                               Pair(name='молоко 3,2%', count='160 мл'),
                                               Pair(name='сироп Pinch&Drop «Попкорн»', count='20 мл'),
                                               Pair(name='эспрессо', count='1 шот'), Pair(name='лед', count='110 г')]}
    update_ontology_graph(cf)
    #response_data: list[str] = urls.get_data_from_urls()
    #data_handler.to_handle(response_data)


if __name__ == '__main__':
    main()
