PREFIX o: <http://www.semanticweb.org/admin/ontologies/2024/9/untitled-ontology-10#>

# Какое блюдо можно приготовить, если мне нужно высокое содержание углеводов (более 50 г) и низкое содержание жиров (менее 10 г)?
SELECT ?recipe ?recipeName ?carbohydrates ?fats
WHERE {
  ?recipe a o:Recipe ;
          o:name ?recipeName ;
          o:carbohydrateContent ?carbohydrates ;
          o:fatContent ?fats .

  FILTER(?carbohydrates > 50 && ?fats < 10)
}
ORDER BY DESC(?carbohydrates)