# Какие рецепты для итальянской кухни подходят для ужина и имеют калорийность менее 500 калорий?
PREFIX o: <http://www.semanticweb.org/admin/ontologies/2024/9/untitled-ontology-10#>

SELECT ?recipe ?recipeName ?calories
WHERE {
  ?recipe a o:Recipe ;
          o:name ?recipeName ;
          o:belongsToCuisine ?cuisine ;
          o:calories ?calories ;
          o:hasCategory ?category .
  
  ?cuisine a o:Cuisine ;
           o:name "Italian" .
  
  ?category a o:Category ;
            o:name "side dish" .
  
  FILTER(?calories < 500)
}
ORDER BY ?calories