PREFIX o: <http://www.semanticweb.org/admin/ontologies/2024/9/untitled-ontology-10#>

# Какие блюда подходят для обеда и содержат не менее 15 грамм белка, но не более 20 грамм жиров?
SELECT ?recipe ?recipeName ?protein ?fats
WHERE {
  ?recipe a o:Recipe ;
          o:name ?recipeName ;
          o:proteinContent ?protein ;
          o:fatContent ?fats ;
          o:hasCategory ?category .

  ?category a o:Category ;
            o:name "lunch" .

  FILTER(?protein >= 15 && ?fats <= 20)
}
ORDER BY DESC(?protein)