# Какие рецепты можно приготовить из овощей и которые соответствуют веганской диете?
PREFIX o: <http://www.semanticweb.org/admin/ontologies/2024/9/untitled-ontology-10#>

SELECT DISTINCT ?recipe ?recipeName
WHERE {
  ?recipe a o:Recipe ;
          o:name ?recipeName ;
          o:hasDietaryRestriction ?diet ;
          o:uses ?ingredient .
  
  ?diet a o:DietaryRestriction ;
        o:name "vegan" .
  
  ?ingredient a o:Ingredient ;
               o:name ?vegIngredient .
  
  FILTER(regex(?vegIngredient, "^(Carrot|Broccoli|Spinach|Peas|Bell_Pepper|Potato|Tomato|Cucumber)$", "i"))
}
ORDER BY ?recipeName