# Какие рецепты можно приготовить менее чем за 20 минут, если учитывать только блюда, которые соответствуют веганской диете?
PREFIX o: <http://www.semanticweb.org/admin/ontologies/2024/9/untitled-ontology-10#>

SELECT ?recipe ?recipeName ?prepTime
WHERE {
  ?recipe a o:Recipe ;
          o:name ?recipeName ;
          o:time ?prepTime ;
          o:hasDietaryRestriction ?diet .
  
  ?diet a o:DietaryRestriction ;
        o:name "vegan" .
  
  FILTER(?prepTime < 20)
}
ORDER BY ?prepTime