# Какие рецепты можно приготовить для вегетарианцев с использованием ингредиентов "Tomato" и "Garlic"?
PREFIX o: <http://www.semanticweb.org/admin/ontologies/2024/9/untitled-ontology-10#>

SELECT DISTINCT ?recipe ?recipeName
WHERE {
  ?recipe a o:Recipe ;
          o:name ?recipeName ;
          o:hasDietaryRestriction ?diet ;
          o:uses ?ingredient .
  
  ?diet a o:DietaryRestriction ;
        o:name "vegan" .

  ?ingredient1 a o:Ingredient ;
               o:name "tomato" .

  ?ingredient2 a o:Ingredient ;
               o:name "garlic" .
  
  FILTER(EXISTS {
    ?recipe o:uses ?ingredient1 .
    ?recipe o:uses ?ingredient2 .
  })
}
ORDER BY ?recipeName