SELECT DISTINCT ?song ?songLabel ?artistLabel ?genreLabel ?publicationDate WHERE {
#   FILTER (?song = wd:Q21172725)
  ?artist rdfs:label <$ARTIST_LABEL$>@en.
  # we need either composer (classical music, for example) or performer (pop) and it's hard to tell what exactly, so include both.
  {?song wdt:P175 ?artist.} UNION {?song wdt:P86 ?artist.}
  ?song p:P31/ps:P31/(p:P279|ps:P279)* wd:Q105543609.
  OPTIONAL { ?song wdt:P577 ?publicationDate }
  OPTIONAL { ?song wdt:P136 ?genre }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}