PREFIX chp: <http://iburakov.me/ontologies/chord-progressions#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# - Какие аккордовые последовательности популярны у конкретного исполнителя?

SELECT ?abs_chord_repr ?next_abs_chord_repr (COUNT(?progression_entry) as $count)  WHERE {
	?progression_entry a chp:ChordProgressionEntry ;
		chp:hasAbsoluteChord ?abs_chord ;
		chp:hasNextEntry ?next_progression_entry .
	?next_progression_entry a chp:ChordProgressionEntry ;
		chp:hasAbsoluteChord ?abs_chord_next .
    ?abs_chord a chp:AbsoluteChord ;
		chp:hasHookTheoryRepresentation ?abs_chord_repr .
    ?abs_chord_next a chp:AbsoluteChord ;
		chp:hasHookTheoryRepresentation ?next_abs_chord_repr .
	?composition a chp:Composition ;
		chp:hasChordProgression ?progression_entry ;
		chp:hasAuthor ?author.
	?author a chp:Artist ;
    	chp:hasName "Interpol" .
	FILTER (?abs_chord_repr != ?next_abs_chord_repr)
}
GROUP BY ?abs_chord_repr ?next_abs_chord_repr
ORDER BY DESC(?count)
