# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0KKTDFKVTzKR3x3VMfyu7UxcSNzwIE6
"""
import os

import requests
import json

mlist = []
dlist = {}
alist = {}
wlist = {}
clist = {}

KEY = os.getenv("TMDB_API_KEY")

with open("films.json", "w+") as file:
    for page in range(1, 15):
        url = f'https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={page}'

        headers = {
            "accept": "application/json",
            "Authorization": KEY
        }

        response = requests.get(url, headers=headers)
        movie_list = json.loads(response.text)
        films = movie_list['results']

        for f in films:
            writers = []
            actors = []
            composers = []
            directors = []

            film = json.loads(requests.get(f'https://api.themoviedb.org/3/movie/{f["id"]}', headers=headers).text)
            credits = json.loads(
                requests.get(f'https://api.themoviedb.org/3/movie/{f["id"]}/credits', headers=headers).text)
            cast = credits['cast']
            crew = credits['crew']

            for person in cast:
                alist[person['id']] = person['name']
                actors.append(person['id'])

            for person in crew:
                if person['job'] == "Screenplay":
                    wlist[person['id']] = person['name']
                    writers.append(person['id'])
                if person['job'] == "Director":
                    dlist[person['id']] = person['name']
                    directors.append(person['id'])
                if person['job'] == "Original Music Composer":
                    clist[person['id']] = person['name']
                    composers.append(person['id'])

            mlist.append({
                "name": film["original_title"],
                "id": film["id"],
                "overview": film["overview"],
                "poster_url": film["poster_path"],
                "directors": directors,
                "actors": actors,
                "writers": writers,
                "composers": composers,
                "rating": film["vote_average"]
            })

    json.dump({'movies': mlist}, file)

with open("directors.json", "w+") as d:
    json.dump(dlist, d)

with open("actors.json", "w+") as a:
    json.dump(alist, a)

with open("writers.json", "w+") as w:
    json.dump(wlist, w)

with open("composers.json", "w+") as c:
    json.dump(clist, c)

# дальше идет веселье со скачиванием картинок
import shutil

for m in mlist:

    url = f'https://image.tmdb.org/t/p/w600_and_h900_bestv2{m["poster_url"]}'
    path = f'images/{m["id"]}.jpg'
    headers = {
        "accept": "image/jpeg",
        "Authorization": KEY
    }

    r = requests.get(url, headers=headers, stream=True)
    if r.status_code == 200:
        with open(path, 'wb') as f:
            r.raw.decode_content = True
            shutil.copyfileobj(r.raw, f)

from zipfile import ZipFile
import glob

with ZipFile('images.zip', 'w') as archive:
    for filepath in glob.iglob(f'images/*.jpg'):
        archive.write(str(filepath), arcname=filepath[filepath.rfind("/"):])
    archive.close()
