# Какие книги были написаны авторами, родившимися в XVIII веке?

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ons: <http://www.semanticweb.org/admin/ontologies/2024/9/authors-ontology#>

SELECT ?bookTitle ?authorName ?birthDate
WHERE {
    ?author a ons:Author ;
            ons:name ?authorName ;
            ons:birthDate ?birthDate ;
            ons:wroteBook ?book .
    ?book a ons:Book ;
          ons:name ?bookTitle .

    FILTER ( ?birthDate >= "1701-01-01"^^xsd:date && ?birthDate <= "1800-12-31"^^xsd:date )
}
#"Eugene Onegin"	"Alexander Pushkin"	"1799-06-06"^^<http://www.w3.org/2001/XMLSchema#date>	
#"Boris Godunov Play"	"Alexander Pushkin"	"1799-06-06"^^<http://www.w3.org/2001/XMLSchema#date>	
#"Ruslan And Ludmila"	"Alexander Pushkin"	"1799-06-06"^^<http://www.w3.org/2001/XMLSchema#date>	
#"The Captains Daughter"	"Alexander Pushkin"	"1799-06-06"^^<http://www.w3.org/2001/XMLSchema#date>	
#"Rimen En Teltsjes"	"Eeltsje Hiddes Halbertsma"	"1797-10-08"^^<http://www.w3.org/2001/XMLSchema#date>	
#"De Alde Friezen"	"Eeltsje Hiddes Halbertsma"	"1797-10-08"^^<http://www.w3.org/2001/XMLSchema#date>	
#"Or The Four Zoas"	"William Blake"	"1757-11-28"^^<http://www.w3.org/2001/XMLSchema#date>	
#"Jerusalem The Emanation Of The Giant Albion"	"William Blake"	"1757-11-28"^^<http://www.w3.org/2001/XMLSchema#date>
# .........................
#"Nans Satomi Hakkenden"	"Takizawa Bakin"	"1767-07-04"^^<http://www.w3.org/2001/XMLSchema#date>