# Сколько известных книг написал Фёдор Достоевский?

PREFIX ons: <http://www.semanticweb.org/admin/ontologies/2024/9/authors-ontology#>
SELECT (COUNT(DISTINCT ?book) AS ?bookCount)
WHERE {
    ?author a ons:Author ;
            ons:name "Fyodor Dostoevsky" ;
            ons:wroteBook ?book .
    ?book a ons:Book .
}
#"5"^^<http://www.w3.org/2001/XMLSchema#integer>