# Кто написал больше книг: Фёдор Достоевский или Александр Пушкин?
PREFIX ons: <http://www.semanticweb.org/admin/ontologies/2024/9/authors-ontology#>
SELECT ?authorName (COUNT(DISTINCT ?book) AS ?bookCount)
WHERE {
    ?author a ons:Author ;
            ons:name ?authorName ;
            ons:wroteBook ?book .
    FILTER (?authorName IN ("Fyodor dostoevsky", "Alexander Pushkin"))
}
GROUP BY ?authorName

#answer "Alexander Pushkin"	"4"^^<http://www.w3.org/2001/XMLSchema#integer>