# Какие авторы из Нигерии родились после 1900 года?
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ons: <http://www.semanticweb.org/admin/ontologies/2024/9/authors-ontology#>

SELECT ?authorName ?birthDate
WHERE {
    ?author a ons:Author ;
            ons:name ?authorName ;
            ons:birthDate ?birthDate ;
            ons:hasNationalityOrLanguage ?nat .
    ?nat ons:name "Nigeria" .

    FILTER ( ?birthDate > "1900-01-01"^^xsd:date )
}
#"Akwaeke Emezi"	"1987-06-06"^^<http://www.w3.org/2001/XMLSchema#date>	
#"Jordan Ifueko"	"1993-08-16"^^<http://www.w3.org/2001/XMLSchema#date>