# Какие книги в жанре «роман» были написаны российскими авторами?

PREFIX ons: <http://www.semanticweb.org/admin/ontologies/2024/9/authors-ontology#>

SELECT ?bookTitle ?authorName
WHERE {
    ?author a ons:Author ;
            ons:name ?authorName ;
            ons:hasGenre ?genre ;
            ons:hasNationalityOrLanguage ?nationality ;
            ons:wroteBook ?book .
    
    ?genre ons:name "Novel" .
    ?nationality ons:name "Russian" .  
    
    ?book a ons:Book ;
          ons:name ?bookTitle .
}

#answer "Eugene Onegin"	"Alexander Pushkin"	
#"Boris Godunov Play"	"Alexander Pushkin"	
#"Ruslan And Ludmila"	"Alexander Pushkin"	
#"The Captains Daughter"	"Alexander Pushkin"