# -*- coding: utf-8 -*-
"""экзамен "IIP+ATO demo.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18AJDqwlj3WNSP-YtwFQwLSdloh_gkAZx

Инсталлируем rdflib
"""

!pip install rdflib
!pip install PyDrive

from rdflib import URIRef, BNode, Literal, Namespace, Graph
from rdflib.namespace import Namespace, NamespaceManager
from rdflib.plugins import sparql
from rdflib.namespace import RDF, RDFS, XSD
from rdflib.serializer import Serializer

"""открываем диск и загружаем онтологию"""

from google.colab import drive
drive.mount('/content/drive')
#!ls '/content/drive/MyDrive/Colab Notebooks/IIP+ATO'

# Create an emprty graph
g = Graph()
ontology_url = '/content/drive/MyDrive/onlogi/12345678.owl'

g.parse(ontology_url, format="json-ld")
print(len(g))

print (g.serialize(format='n3'))

"""Cмотрим какими статистическими свойствами облдают герои """

q_1 = """
    SELECT ?x WHERE{ ?x a owl:DatatypeProperty .
       
    }
"""

for row in g.query(q_1):
    print(row.x)

"""Смотрим mai роли героев """

q_2 = """
    SELECT ?y WHERE{ ?y a owl:FunctionalProperty,
        owl:ObjectProperty.
       
    }
"""

for row in g.query(q_2):
    print(row.y)

"""смотрим свойсва героев основанные на статистике"""

q_3 = """
    SELECT ?z WHERE{ ?z a owl:ObjectProperty.
      
       
    }
"""

for row in g.query(q_3):
    print(row.z)

"""Смотрим состав онтологии 


> Блок с отступами


"""

q_4 = """
    SELECT ?c WHERE{ ?c a owl:Class.
      
       
    }
"""

for row in g.query(q_4):
    print(row.c)